# Generated by Django 6.0.7 on 2026-07-15 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('settings_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='settings_manager.currency'),
        ),
        migrations.CreateModel(
            name='PaymentProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(unique=True)),
                ('apply_tax', models.BooleanField(default=True, help_text='Designates whether tax is applied on bookings using this processor')),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Processor',
                'verbose_name_plural': 'Payment Processors',
            },
        ),
        migrations.CreateModel(
            name='PaymentProcessorCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings_manager.currency')),
                ('payment_processor', models.ForeignKey(db_column='payment_processor_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payments.paymentprocessor')),
            ],
            options={
                'db_table': 'payments_paymentprocessor_payment_currencies',
            },
        ),
        migrations.AddField(
            model_name='paymentprocessor',
            name='payment_currencies',
            field=models.ManyToManyField(related_name='supported_by_processors', through='payments.PaymentProcessorCurrency', to='settings_manager.currency'),
        ),
        migrations.AddIndex(
            model_name='paymentprocessorcurrency',
            index=models.Index(fields=['payment_processor', 'currency'], name='payments_pa_payment_edd5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentprocessor',
            index=models.Index(fields=['is_published'], name='payments_pa_is_publ_c13752_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentprocessor',
            index=models.Index(fields=['code'], name='payments_pa_code_780ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentprocessor',
            index=models.Index(fields=['is_published', 'id'], name='payments_pa_is_publ_35551f_idx'),
        ),
    ]
