# Generated by Django 6.0.7 on 2026-09-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_addon_price_type'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_custom_addons',
            field=models.BooleanField(default=True, help_text='Allow guests to choose optional paid add-ons during room booking'),
        ),
        migrations.AddField(
            model_name='room',
            name='included_addons',
            field=models.ManyToManyField(blank=True, help_text='Included complimentary Add-on services (e.g. Free Breakfast, Airport Shuttle)', related_name='rooms', to='booking.addon'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, help_text='Room number / Room code (e.g. 101, 102, Villa A)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total physical rooms available for this specific room listing'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, default='King Size', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='highlights',
            field=models.TextField(blank=True, help_text='Comma-separated or line-separated list of room highlights', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.IntegerField(blank=True, help_text='Size in sq. ft. or sq. meters', null=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Legacy physical room count (deprecated - managed on Room model)', null=True),
        ),
    ]
