# Generated by Django 6.0.7 on 2026-07-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total number of physical rooms of this type'),
        ),
    ]
