# Generated by Django 6.0.7 on 2026-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('NPR', 'NPR (₨)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='USD', help_text='Currency of the base and discount price', max_length=3),
        ),
        migrations.AddField(
            model_name='room',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this room is visible on the website'),
        ),
    ]
