# Generated by Django 6.0.7 on 2026-07-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_add_total_rooms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomavailability',
            unique_together=set(),
        ),
    ]
