# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_currency_room_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('rooms/gallery'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
