# Generated by Django 6.0.7 (manually enhanced with data migration)

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CATEGORIES = [
    ('deluxe',          'Deluxe Room',           1),
    ('super_deluxe',    'Super Deluxe Room',      2),
    ('premium',         'Premium Room',           3),
    ('premium_suite',   'Premium Junior Suite',   4),
    ('deluxe_suite',    'Deluxe Suite',           5),
    ('honeymoon_suite', 'Honeymoon Suite',        6),
    ('executive',       'Executive Room',         7),
]


def seed_categories(apps, schema_editor):
    """Step 1: Create default RoomCategory rows."""
    RoomCategory = apps.get_model('rooms', 'RoomCategory')
    for slug, name, order in DEFAULT_CATEGORIES:
        RoomCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'order': order, 'is_published': True}
        )


def migrate_room_categories(apps, schema_editor):
    """
    Step 2 (after AlterField): Update category_id FK on rooms using raw SQL
    so we look up the RoomCategory pk by its slug (which matched the old string value).
    """
    db = schema_editor.connection
    RoomCategory = apps.get_model('rooms', 'RoomCategory')
    for slug, _, _ in DEFAULT_CATEGORIES:
        try:
            cat = RoomCategory.objects.get(slug=slug)
        except RoomCategory.DoesNotExist:
            continue
        with db.cursor() as cursor:
            cursor.execute(
                "UPDATE rooms_room SET category_id = %s WHERE category_id = %s",
                [cat.pk, slug]
            )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomimage_image'),
    ]

    operations = [
        # 1. Create RoomCategory table
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category display name, e.g. 'Deluxe Room'", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Auto-generated URL-safe key, e.g. 'deluxe'", max_length=120, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in dropdowns and filters')),
                ('is_published', models.BooleanField(default=True, help_text='Show this category in room filters and admin dropdowns')),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'ordering': ['order', 'name'],
            },
        ),

        # 2. Seed the categories BEFORE the column type changes
        migrations.RunPython(seed_categories, reverse_migration),

        # 3. Change column from VARCHAR (slug) → INTEGER FK
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Room category (managed in admin under Room Categories)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rooms',
                to='rooms.roomcategory',
            ),
        ),

        # 4. After AlterField: remap category_id values using raw SQL
        migrations.RunPython(migrate_room_categories, reverse_migration),
    ]
