# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearby_places', '0002_alter_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('attractions'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
