# Generated by Django 6.0.7 on 2026-07-28 10:39

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningVenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('dining/gallery'), validators=[core.utils.ValidateFileSize(2)])),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text for screen readers', max_length=200)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dining.diningvenue')),
            ],
            options={
                'verbose_name': 'Dining Venue Image',
                'verbose_name_plural': 'Dining Venue Images',
            },
        ),
    ]
