# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_alter_diningvenue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningvenue',
            name='chef_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('dining/chefs'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AlterField(
            model_name='diningvenue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('dining/venues'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
