# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_alter_diningvenue_chef_image_alter_diningvenue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningvenue',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this dining venue is visible on the website'),
        ),
    ]
