# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this gallery category is visible on the website'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this gallery item is visible on the website'),
        ),
    ]
