# Generated by Django 6.0.7 on 2026-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningvenue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dining/venues/'),
        ),
    ]
