# Generated by Django 6.0.7 on 2026-09-14 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('maps_iframe', models.TextField(blank=True, help_text='Google Maps iframe embed code', null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this branch is visible on the website')),
            ],
            options={
                'verbose_name': 'Hotel Branch',
                'verbose_name_plural': 'Hotel Branches',
            },
        ),
        migrations.CreateModel(
            name='InquiryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief description or purpose of this category', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is active and visible in the contact form')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display sort order sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry Category',
                'verbose_name_plural': 'Inquiry Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email ownership verified via double opt-in')),
                ('is_active', models.BooleanField(default=False, help_text='Active subscriber status')),
                ('verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Designates whether this inquiry has been viewed by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category/nature of the inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='contact.inquirycategory')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
