# Generated by Django 6.0.7 on 2026-08-18 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email ownership verified via double opt-in')),
                ('is_active', models.BooleanField(default=False, help_text='Active subscriber status')),
                ('verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ('-created_at',),
            },
        ),
    ]
