# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this branch is visible on the website'),
        ),
    ]
