# Generated by Django 6.0.7 on 2026-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Designates whether this inquiry has been viewed by admin'),
        ),
    ]
