# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('avatars'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
