# Generated by Django 6.0.7 on 2026-07-18 10:08

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(help_text='Max seating/floating capacity')),
                ('layout_options', models.TextField(help_text='e.g. Theatre: 300, Classroom: 150, Banquet: 200')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Starting price for renting the hall', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('conference'), validators=[core.utils.ValidateFileSize(2)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('guest_count', models.IntegerField()),
                ('catering_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='conference.eventvenue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
