# Generated by Django 6.0.7 on 2026-09-14 11:20

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of this event type')),
                ('image', models.ImageField(blank=True, help_text='Cover/branding photo for marketing showcase', null=True, upload_to=core.utils.UploadTo('conference/event_types'), validators=[core.utils.ValidateFileSize(2)])),
                ('icon', models.CharField(default='fa-calendar-check', help_text='FontAwesome icon class (e.g. fa-ring, fa-handshake, fa-cake-candles, fa-champagne-glasses)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Available for public inquiries')),
                ('is_featured', models.BooleanField(default=False, help_text='Showcase on homepage for branding & marketing')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sorting sequence in lists and dropdowns')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(help_text='Max seating/floating capacity')),
                ('layout_options', models.TextField(blank=True, default='', help_text='e.g. Theatre: 300, Classroom: 150, Banquet: 200')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Legacy fallback price', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('conference'), validators=[core.utils.ValidateFileSize(2)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this hall on homepage')),
                ('allow_custom_addons', models.BooleanField(default=True, help_text='Allow guests to select optional add-on services in the proposal inquiry form')),
                ('available_addons', models.ManyToManyField(blank=True, help_text='Select complimentary add-on services included with this venue package', limit_choices_to={'applies_to__in': ['events', 'both']}, related_name='event_venues', to='booking.addon')),
                ('event_types', models.ManyToManyField(blank=True, help_text='Select event categories / occasions hosted in this banquet venue hall', related_name='venues', to='conference.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='EventVenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('conference/gallery'), validators=[core.utils.ValidateFileSize(2)])),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text for screen readers', max_length=200)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='conference.eventvenue')),
            ],
            options={
                'verbose_name': 'Event Venue Image',
                'verbose_name_plural': 'Event Venue Images',
            },
        ),
        migrations.CreateModel(
            name='VenueLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Theatre, Banquet, Classroom, U-Shape, Boardroom', max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Seating capacity for this layout setup')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='conference.eventvenue')),
            ],
            options={
                'verbose_name': 'Venue Layout',
                'verbose_name_plural': 'Venue Layouts',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('guest_count', models.IntegerField()),
                ('catering_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('processed', 'Processed (Legacy)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addons', models.ManyToManyField(blank=True, help_text='Requested event add-on services', related_name='event_inquiries', to='booking.addon')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='conference.eventtype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='conference.eventvenue')),
                ('preferred_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='conference.venuelayout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_base_prices', to='settings_manager.currency')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='conference.eventvenue')),
            ],
            options={
                'verbose_name': 'Venue Base Price',
                'verbose_name_plural': 'Venue Base Prices',
                'unique_together': {('venue', 'currency')},
            },
        ),
    ]
