# Generated by Django 6.0.7 on 2026-07-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
        ('settings_manager', '0002_hotelsettings_admin_label_hotelsettings_admin_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_base_prices', to='settings_manager.currency')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='conference.eventvenue')),
            ],
            options={
                'verbose_name': 'Venue Base Price',
                'verbose_name_plural': 'Venue Base Prices',
                'unique_together': {('venue', 'currency')},
            },
        ),
    ]
