# Generated by Django 6.0.7 on 2026-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_venuebaseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvenue',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy fallback price', max_digits=10, null=True),
        ),
    ]
