# Generated by Django 6.0.7 on 2026-07-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms booked'),
        ),
    ]
