# Generated by Django 6.0.7 on 2026-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Currency ISO code used when booking was created', max_length=10),
        ),
    ]
