# Generated by Django 6.0.7 on 2026-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='channel_name',
            field=models.CharField(default='direct', help_text='e.g. direct, booking.com, expedia, agoda', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='channel_raw_payload',
            field=models.JSONField(blank=True, help_text='Raw payload received from the channel manager/OTA API', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ota_reservation_id',
            field=models.CharField(blank=True, help_text='Reservation ID from the OTA/channel manager', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Visa/Mastercard'), ('pay_later', 'Pay at Hotel')], default='pay_later', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
