# Generated by Django 6.0.7 on 2026-08-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_coupon_options_coupon_applicable_to_and_more'),
        ('settings_manager', '0002_hotelsettings_admin_label_hotelsettings_admin_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional short summary shown to guests during booking', null=True)),
                ('icon', models.CharField(default='fa-plus-circle', help_text='FontAwesome icon class e.g. fa-utensils, fa-camera, fa-car, fa-bed, fa-spa', max_length=50)),
                ('applies_to', models.CharField(choices=[('both', 'Both Rooms & Services'), ('room', 'Room Bookings Only')], default='room', max_length=20)),
                ('price_type', models.CharField(choices=[('per_night', 'Per Room / Per Night'), ('per_person', 'Per Guest'), ('per_booking', 'Per Room Booking')], default='per_night', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this add-on is available for selection during booking')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Add-on Service',
                'verbose_name_plural': 'Add-on Services',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=150)),
                ('price_type', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_links', to='booking.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons', to='booking.booking')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AddonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='booking.addon')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addon_prices', to='settings_manager.currency')),
            ],
            options={
                'verbose_name': 'Add-on Price',
                'verbose_name_plural': 'Add-on Prices',
                'unique_together': {('addon', 'currency')},
            },
        ),
    ]
