# Generated by Django 6.0.7 on 2026-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_addon_bookingaddon_addonprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='price_type',
            field=models.CharField(choices=[('per_night', 'Per Room / Per Night'), ('per_person', 'Per Guest'), ('per_person_per_night', 'Per Guest / Per Night'), ('per_booking', 'Per Room Booking')], default='per_night', max_length=20),
        ),
    ]
