# Generated by Django 6.0.7 on 2026-09-14 11:20

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Resort', max_length=150)),
                ('subtitle', models.CharField(default='A Haven of Luxury & Hospitality', max_length=250)),
                ('content', models.TextField(help_text='Introductory text about the hotel')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/about'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_file', models.FileField(blank=True, help_text='Uploaded promo video file (MP4/WebM/MOV)', null=True, upload_to=core.utils.UploadTo('homepage/about/videos'), validators=[core.utils.ValidateFileSize(50), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'm4v'])])),
                ('video_url', models.URLField(blank=True, help_text='Promo video YouTube/Vimeo link', null=True)),
                ('stat1_value', models.CharField(default='120', max_length=10)),
                ('stat1_label', models.CharField(default='Luxury Rooms', max_length=50)),
                ('stat2_value', models.CharField(default='5', max_length=10)),
                ('stat2_label', models.CharField(default='Star Rating', max_length=50)),
                ('stat3_value', models.CharField(default='3', max_length=10)),
                ('stat3_label', models.CharField(default='Elite Restaurants', max_length=50)),
                ('stat4_value', models.CharField(default='15+', max_length=10)),
                ('stat4_label', models.CharField(default='Awards Won', max_length=50)),
                ('search_button_text', models.CharField(default='Search Rooms', help_text='Search widget button text', max_length=50)),
                ('rooms_badge', models.CharField(default='Premium Sanctuary', help_text='Featured rooms section badge', max_length=100)),
                ('rooms_title', models.CharField(default='Rooms & Suites', help_text='Featured rooms section title', max_length=150)),
                ('rooms_subtitle', models.CharField(default='Explore our signature guest chambers designed for ultimate relaxation and comfort.', help_text='Featured rooms section subtitle', max_length=255)),
                ('facilities_badge', models.CharField(default='Elite Hospitality', help_text='Facilities section badge', max_length=100)),
                ('facilities_title', models.CharField(default='Resort Services & Facilities', help_text='Facilities section title', max_length=150)),
                ('facilities_subtitle', models.CharField(default='Indulge in our carefully curated amenities, designed to elevate your stay to a world-class level.', help_text='Facilities section subtitle', max_length=255)),
                ('dining_badge', models.CharField(default='Fine Culinary', help_text='Dining preview section badge', max_length=100)),
                ('dining_title', models.CharField(default='Gastronomy & Lounge', help_text='Dining preview section title', max_length=150)),
                ('dining_subtitle', models.CharField(default='Savor international delicacies, authentic Nepalese cuisine, and masterfully mixed cocktails curated by globally acclaimed chefs.', help_text='Dining preview section subtitle', max_length=255)),
                ('dining_button_text', models.CharField(default='Explore More', help_text='Dining preview explore button text', max_length=50)),
                ('testimonials_badge', models.CharField(default='Guest Memoirs', help_text='Testimonials section badge', max_length=100)),
                ('testimonials_title', models.CharField(default='What Our Guests Say', help_text='Testimonials section title', max_length=150)),
                ('attractions_badge', models.CharField(default='Explore Nearby', help_text='Attractions section badge', max_length=100)),
                ('attractions_title', models.CharField(default='Local Sights & Attractions', help_text='Attractions section title', max_length=150)),
                ('newsletter_badge', models.CharField(default='Newsletter Subscription', help_text='Newsletter section badge', max_length=100)),
                ('newsletter_title', models.CharField(default='Join The Elite Guild', help_text='Newsletter section title', max_length=150)),
                ('newsletter_subtitle', models.CharField(default='Subscribe to receive exclusive offers, luxury travel logs, seasonal booking discounts, and resort news.', help_text='Newsletter section subtitle', max_length=255)),
                ('newsletter_button_text', models.CharField(default='Subscribe', help_text='Newsletter submit button text', max_length=50)),
                ('newsletter_image', models.ImageField(blank=True, help_text='Background photo for newsletter banner', null=True, upload_to=core.utils.UploadTo('homepage/newsletter'), validators=[core.utils.ValidateFileSize(3)])),
            ],
            options={
                'verbose_name': 'Homepage CMS Settings',
                'verbose_name_plural': 'Homepage CMS Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/hero'), validators=[core.utils.ValidateFileSize(2)])),
                ('background_video_url', models.URLField(blank=True, help_text='YouTube or direct MP4 link', null=True)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Dark overlay opacity (0.00 to 1.00)', max_digits=3)),
                ('cta_text', models.CharField(default='Discover More', max_length=50)),
                ('cta_url', models.CharField(default='/rooms/', max_length=200)),
                ('cta2_text', models.CharField(blank=True, default='Book Now', max_length=50, null=True)),
                ('cta2_url', models.CharField(blank=True, default='/booking/', max_length=200, null=True)),
                ('title_animation', models.CharField(choices=[('fadeInDown', 'Fade In Down'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right')], default='fadeInDown', max_length=50)),
                ('subtitle_animation', models.CharField(choices=[('fadeInDown', 'Fade In Down'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right')], default='fadeInUp', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
