# Generated by Django 6.0.7 on 2026-07-28 06:20

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpreview',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded promo video file (MP4/WebM/MOV)', null=True, upload_to=core.utils.UploadTo('homepage/about/videos'), validators=[core.utils.ValidateFileSize(50), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'm4v'])]),
        ),
        migrations.AlterField(
            model_name='aboutpreview',
            name='title',
            field=models.CharField(default='About Our Resort', max_length=150),
        ),
    ]
