# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/about'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/hero'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
