# Generated by Django 6.0.7 on 2026-08-20 06:19

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_aboutpreview_video_file_alter_aboutpreview_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpreview',
            options={'verbose_name': 'Homepage CMS Settings', 'verbose_name_plural': 'Homepage CMS Settings'},
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='attractions_badge',
            field=models.CharField(default='Explore Nearby', help_text='Attractions section badge', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='attractions_title',
            field=models.CharField(default='Local Sights & Attractions', help_text='Attractions section title', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='dining_badge',
            field=models.CharField(default='Fine Culinary', help_text='Dining preview section badge', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='dining_button_text',
            field=models.CharField(default='Explore More', help_text='Dining preview explore button text', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='dining_subtitle',
            field=models.CharField(default='Savor international delicacies, authentic Nepalese cuisine, and masterfully mixed cocktails curated by globally acclaimed chefs.', help_text='Dining preview section subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='dining_title',
            field=models.CharField(default='Gastronomy & Lounge', help_text='Dining preview section title', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='facilities_badge',
            field=models.CharField(default='Elite Hospitality', help_text='Facilities section badge', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='facilities_subtitle',
            field=models.CharField(default='Indulge in our carefully curated amenities, designed to elevate your stay to a world-class level.', help_text='Facilities section subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='facilities_title',
            field=models.CharField(default='Resort Services & Facilities', help_text='Facilities section title', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='newsletter_badge',
            field=models.CharField(default='Newsletter Subscription', help_text='Newsletter section badge', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='newsletter_button_text',
            field=models.CharField(default='Subscribe', help_text='Newsletter submit button text', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='newsletter_image',
            field=models.ImageField(blank=True, help_text='Background photo for newsletter banner', null=True, upload_to=core.utils.UploadTo('homepage/newsletter'), validators=[core.utils.ValidateFileSize(3)]),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='newsletter_subtitle',
            field=models.CharField(default='Subscribe to receive exclusive offers, luxury travel logs, seasonal booking discounts, and resort news.', help_text='Newsletter section subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='newsletter_title',
            field=models.CharField(default='Join The Elite Guild', help_text='Newsletter section title', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='rooms_badge',
            field=models.CharField(default='Premium Sanctuary', help_text='Featured rooms section badge', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='rooms_subtitle',
            field=models.CharField(default='Explore our signature guest chambers designed for ultimate relaxation and comfort.', help_text='Featured rooms section subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='rooms_title',
            field=models.CharField(default='Rooms & Suites', help_text='Featured rooms section title', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='search_button_text',
            field=models.CharField(default='Search Rooms', help_text='Search widget button text', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='testimonials_badge',
            field=models.CharField(default='Guest Memoirs', help_text='Testimonials section badge', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpreview',
            name='testimonials_title',
            field=models.CharField(default='What Our Guests Say', help_text='Testimonials section title', max_length=150),
        ),
    ]
