# Generated by Django 6.0.7 on 2026-08-20 05:45

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='fa-solid fa-star', help_text='FontAwesome icon class (e.g., fa-solid fa-spa)', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Facility Highlight',
                'verbose_name_plural': 'About Facility Highlights',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default="⭐ Nepal's First 5-Star Hotel in Simara", max_length=100)),
                ('hero_title', models.CharField(default='Epitome of Luxury & Sophistication', max_length=200)),
                ('hero_subtitle', models.CharField(default='Hotel Ichchha — Simara, Bara, Nepal', max_length=250)),
                ('hero_description', models.TextField(default='A verdant oasis in the heart of Simara offering exceptional comfort, convenience, enjoyment, and five-star hospitality services.')),
                ('hero_image', models.ImageField(blank=True, help_text='Background hero banner image', null=True, upload_to=core.utils.UploadTo('about/hero'), validators=[core.utils.ValidateFileSize(5)])),
                ('story_badge', models.CharField(default='Our Legacy & Heritage', max_length=100)),
                ('story_title', models.CharField(default='A Verdant Oasis in the Heart of Simara', max_length=200)),
                ('story_subtitle', models.CharField(default="Redefining Five-Star Hospitality in Nepal's Southern Gateway", max_length=250)),
                ('story_content', models.TextField(default='Being a top hospitality provider in Nepal, Hotel Ichchha guarantees finest offerings due to its convenient location in Simara, Bara. It is the premier choice for business executives, leisure seekers, destination weddings, and pilgrimage journeys. With 96 exquisitely appointed rooms and suites, multiple dining venues, a serene wellness spa, expansive conference halls, and lush gardens, Hotel Ichchha sets a new benchmark in guest experience and luxury service excellence.', help_text='Detailed story and overview of Hotel Ichchha')),
                ('story_image_1', models.ImageField(blank=True, help_text='Primary story showcase image', null=True, upload_to=core.utils.UploadTo('about/story'), validators=[core.utils.ValidateFileSize(5)])),
                ('story_image_2', models.ImageField(blank=True, help_text='Secondary story showcase image', null=True, upload_to=core.utils.UploadTo('about/story'), validators=[core.utils.ValidateFileSize(5)])),
                ('stat1_value', models.CharField(default='96', max_length=20)),
                ('stat1_label', models.CharField(default='Luxury Rooms & Suites', max_length=60)),
                ('stat2_value', models.CharField(default='5-Star', max_length=20)),
                ('stat2_label', models.CharField(default='Luxury Rating', max_length=60)),
                ('stat3_value', models.CharField(default='27+', max_length=20)),
                ('stat3_label', models.CharField(default='Years Industry Leadership', max_length=60)),
                ('stat4_value', models.CharField(default='1,000+', max_length=20)),
                ('stat4_label', models.CharField(default='Banqueting Pax Capacity', max_length=60)),
                ('ceo_title', models.CharField(default='Message from the CEO', max_length=200)),
                ('ceo_subtitle', models.CharField(default='We are committed to providing the best hospitality services to our guests.', max_length=250)),
                ('ceo_name', models.CharField(default='Rewanta Prasad Dhaubhadel', max_length=150)),
                ('ceo_role', models.CharField(default='Chief Executive Officer (CEO)', max_length=150)),
                ('ceo_image', models.ImageField(blank=True, help_text='CEO portrait image', null=True, upload_to=core.utils.UploadTo('about/ceo'), validators=[core.utils.ValidateFileSize(5)])),
                ('ceo_quote', models.TextField(default='With a heart rooted in tradition and eyes set on innovation, I remain committed to advancing Nepal’s hospitality industry and creating opportunities for sustainable growth and global recognition.')),
                ('ceo_message', models.TextField(default='Namaste,\n\nMy name is Rewanta Prasad Dhaubhadel, though I’m more fondly known as Rebu by friends, family, and colleagues. With over 27 years of experience in the hospitality industry, my journey has been deeply rooted in a passion for service, excellence, and continuous growth.\n\nI began my career with a formal education in hospitality, earning a Hotel Management Degree from the prestigious Swiss Hotel Management School. My early professional experiences in Switzerland—across cities like Geneva, Lausanne, and Montreux—provided a strong foundation in global standards and refined hospitality practices.\n\nUpon returning to Nepal, I took on various leadership roles in the country’s hospitality sector, including at the renowned Hotel Royal Singi, contributing to the dynamic tourism and service landscape of the Kathmandu Valley. I’ve also had the honor of mentoring the next generation of hoteliers as a faculty member at GATE College, sharing both my international insights and local expertise.\n\nCurrently, I serve as the Chief Executive Officer of Hotel Ichchha – Simara, a leading establishment in Nepal’s southern plains. In this role, I am driven by a vision to unlock the immense potential of Simara, transforming it into a premier hospitality destination that not only uplifts the local economy but also sets new benchmarks in guest experience and service excellence.', help_text='Full CEO narrative and message')),
                ('ceo_signature_text', models.CharField(default='Rewanta Prasad Dhaubhadel (Rebu)', max_length=150)),
                ('mission_title', models.CharField(default='Our Mission', max_length=150)),
                ('mission_text', models.TextField(default='To deliver authentic Nepalese warmth fused with international 5-star hospitality standards, creating unforgettable memories for every guest who walks through our doors.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=150)),
                ('vision_text', models.TextField(default="To be recognized as Nepal's premier luxury destination resort and conference hub, setting the standard for sustainable tourism and world-class service.")),
                ('values_title', models.CharField(default='Our Core Values', max_length=150)),
                ('values_text', models.TextField(default='Guest-centric excellence, uncompromising integrity, cultural pride, culinary artistry, and passionate commitment to environmental sustainability.')),
                ('video_badge', models.CharField(default='Visual Experience', max_length=100)),
                ('video_title', models.CharField(default='Discover the Spirit of Hotel Ichchha', max_length=200)),
                ('video_subtitle', models.CharField(default='Immerse yourself in a virtual tour of our resort, serene pools, luxury suites, and banquets.', max_length=250)),
                ('video_url', models.URLField(blank=True, default='https://hotelichchha.com/backend/images/articles/video/LAeuf-intro_video--hqhIzqZ.mp4', help_text='Direct MP4 video URL or YouTube/Vimeo link', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload custom MP4/WebM video', null=True, upload_to=core.utils.UploadTo('about/videos'), validators=[core.utils.ValidateFileSize(50), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'm4v'])])),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Cover poster image for the video player', null=True, upload_to=core.utils.UploadTo('about/video_posters'), validators=[core.utils.ValidateFileSize(5)])),
                ('cta_title', models.CharField(default='Plan Your Unforgettable Stay in Simara', max_length=200)),
                ('cta_subtitle', models.CharField(default='Whether you are traveling for business, leisure, or a grand wedding, we await to welcome you.', max_length=250)),
                ('cta_button_text', models.CharField(default='Book A Stay', max_length=60)),
                ('cta_button_url', models.CharField(default='/rooms/', max_length=200)),
                ('cta_secondary_button_text', models.CharField(default='Contact Concierge', max_length=60)),
                ('cta_secondary_button_url', models.CharField(default='/contact/', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page CMS Settings',
                'verbose_name_plural': 'About Page CMS Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=150)),
                ('role', models.CharField(help_text='Designation (e.g., Chairman, Director, CEO)', max_length=150)),
                ('bio', models.TextField(help_text='Short bio and professional experience summary')),
                ('image', models.ImageField(blank=True, help_text='Profile portrait photo', null=True, upload_to=core.utils.UploadTo('about/team'), validators=[core.utils.ValidateFileSize(5)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering sequence in the team grid')),
                ('is_published', models.BooleanField(default=True, help_text='Whether to display this member on the live site')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='X / Twitter profile URL', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Team Member',
                'verbose_name_plural': 'Leadership Team Members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
