# Generated by Django 6.0.7 on 2026-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='team_badge',
            field=models.CharField(default='Visionary Governance', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_subtitle',
            field=models.CharField(default='Unveil the talented individuals who embark on a collective mission to elevate your experience at Hotel Ichchha.', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title',
            field=models.CharField(default='Get to Know the Faces Behind Our Success', max_length=200),
        ),
    ]
