# Generated by Django 6.0.7 on 2026-08-20 06:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_team_badge_aboutpage_team_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='ceo_badge',
            field=models.CharField(default='Executive Leadership', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ceo_credentials',
            field=models.CharField(default='Swiss Hotel Mgmt School Alumnus', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ceo_designation',
            field=models.CharField(default='Chief Executive Officer • Hotel Ichchha', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_badge',
            field=models.CharField(default='Reservations & Inquiries', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Background photo for bottom call to action banner', null=True, upload_to=core.utils.UploadTo('about/cta'), validators=[core.utils.ValidateFileSize(5)]),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='facilities_badge',
            field=models.CharField(default='World-Class Comfort', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='facilities_subtitle',
            field=models.CharField(default='Everything you need for an unmatched stay, relaxing wellness retreat, or grand conference event in Simara.', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='facilities_title',
            field=models.CharField(default='Comprehensive 5-Star Amenities', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_button_text',
            field=models.CharField(default='Book A Stay', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_button_url',
            field=models.CharField(default='/rooms/', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_secondary_button_text',
            field=models.CharField(default='Our Heritage', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_secondary_button_url',
            field=models.CharField(default='#story', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_1_icon',
            field=models.CharField(default='fa-solid fa-bed', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_1_text',
            field=models.CharField(default='96 Luxury Rooms', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_2_icon',
            field=models.CharField(default='fa-solid fa-ring', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_2_text',
            field=models.CharField(default='Destination Weddings', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_3_icon',
            field=models.CharField(default='fa-solid fa-plane-arrival', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_3_text',
            field=models.CharField(default='Simara Airport 5 Min', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_4_icon',
            field=models.CharField(default='fa-solid fa-spa', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_4_text',
            field=models.CharField(default='Ayurvedic Spa', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_5_icon',
            field=models.CharField(default='fa-solid fa-utensils', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_5_text',
            field=models.CharField(default='Gourmet Dining', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_6_icon',
            field=models.CharField(default='fa-solid fa-users-rectangle', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_feature_6_text',
            field=models.CharField(default='1,000+ Pax Hall', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_floating_badge',
            field=models.CharField(default='5-Star Certified', max_length=80),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_subtitle',
            field=models.CharField(default='Whether you are traveling for business, leisure, or a grand wedding celebration, our dedicated team awaits to welcome you.', max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default="Nepal's First 5-Star Hotel in Simara", max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='stat3_label',
            field=models.CharField(default='Years Hospitality Leadership', max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_badge',
            field=models.CharField(default='Our Heritage & Story', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_badge',
            field=models.CharField(default='Resort Visual Tour', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_subtitle',
            field=models.CharField(default='Take a glimpse into our lush resort grounds, sparkling pool, plush suites, and banquet venues.', max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_title',
            field=models.CharField(default='Experience Hotel Ichchha in Motion', max_length=200),
        ),
    ]
