# Generated by Django 6.0.7 on 2026-07-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hotel Ichha', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logos/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark mode logo version', null=True, upload_to='settings/logos/')),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('luxury', 'Luxury Gold Mode'), ('festival', 'Festival Theme')], default='luxury', max_length=20)),
                ('contact_phone', models.CharField(default='+977-1-4XXXXXX', max_length=20)),
                ('contact_email', models.EmailField(default='info@hotelichha.com', max_length=254)),
                ('address', models.CharField(default='Bara, Nepal', max_length=255)),
                ('google_maps_iframe', models.TextField(blank=True, help_text='Google Maps HTML embed iframe', null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('tripadvisor_url', models.URLField(blank=True, null=True)),
                ('about_text', models.TextField(default='A premium 5-star experience of hospitality and luxury.')),
                ('copyright_text', models.CharField(default='&copy; 2026 Hotel Ichha. All Rights Reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Hotel Global Settings',
                'verbose_name_plural': 'Hotel Global Settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(help_text='e.g. /rooms/ or https://booking.com', max_length=200)),
                ('position', models.CharField(choices=[('header', 'Header Main Navigation'), ('footer_links', 'Footer Quick Links'), ('footer_services', 'Footer Our Services'), ('footer_ota', 'Footer OTA Partners')], default='header', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='settings_manager.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
