# Generated by Django 6.0.7 on 2026-07-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. USD, NPR, EUR, GBP', max_length=3, unique=True)),
                ('name', models.CharField(help_text='e.g. US Dollar, Nepalese Rupee', max_length=50)),
                ('symbol', models.CharField(help_text='e.g. $, ₨, €, £', max_length=5)),
                ('rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Conversion rate relative to 1 USD (base)', max_digits=10)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublishing a currency hides it from the UI switcher and uses fallback')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default fallback currency if user has not selected one')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
    ]
