# Generated by Django 6.0.7 on 2026-07-14 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['sequence', 'id']},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='display_name',
            field=models.GeneratedField(db_persist=True, expression=models.F('name'), output_field=models.CharField(max_length=128)),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(default='USD', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='sequence',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['iso_code'], name='settings_ma_iso_cod_695d7c_idx'),
        ),
    ]
