# Generated by Django 6.0.7 on 2026-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_hotelsettings_admin_label_hotelsettings_admin_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='inquiry_notification_email',
            field=models.EmailField(default='info@hotelichchha.com', help_text='Email address to receive instant notifications for new guest inquiries and contact queries', max_length=254),
        ),
    ]
