# Generated by Django 6.0.7 on 2026-08-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0003_hotelsettings_inquiry_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='awards_text',
            field=models.CharField(default='Awards: World Luxury Hotel Winner 2026', help_text='Footer awards accreditation text', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='contact_form_button_text',
            field=models.CharField(default='Submit Inquiry Message', help_text='Contact page form submit button text', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='contact_form_subtitle',
            field=models.CharField(default='Have a custom event or dining reservation question? Complete the form below.', help_text='Contact page form subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='contact_form_title',
            field=models.CharField(default='Send an Inquiry', help_text='Contact page form heading', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='header_badge',
            field=models.CharField(default='⭐ 5-Star Luxury Resort', help_text='Top header information badge', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='header_cta_text',
            field=models.CharField(default='Book A Stay', help_text='Header navigation button text', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='header_cta_url',
            field=models.CharField(default='/rooms/', help_text='Header navigation button URL', max_length=200),
        ),
    ]
