# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0004_currency_created_by_currency_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('settings/logos'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Dark mode logo version', null=True, upload_to=core.utils.UploadTo('settings/logos'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
