# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0005_alter_hotelsettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this menu item is visible on the website'),
        ),
    ]
