# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonial_guest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this testimonial is visible on the website'),
        ),
    ]
