# Generated by Django 6.0.7 on 2026-07-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or Lucide icon class', max_length=100, null=True)),
                ('svg_path', models.TextField(blank=True, help_text='Raw SVG path data or SVG code for rendering custom icons', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Room Facility',
                'verbose_name_plural': 'Room Facilities',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('deluxe', 'Deluxe Room'), ('super_deluxe', 'Super Deluxe Room'), ('premium', 'Premium Room'), ('premium_suite', 'Premium Junior Suite'), ('deluxe_suite', 'Deluxe Suite'), ('honeymoon_suite', 'Honeymoon Suite'), ('executive', 'Executive Room')], default='deluxe', max_length=50)),
                ('description', models.TextField()),
                ('highlights', models.TextField(help_text='Comma-separated or line-separated list of room highlights')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('room_size', models.IntegerField(help_text='Size in sq. ft. or sq. meters')),
                ('max_adults', models.IntegerField(default=2)),
                ('max_children', models.IntegerField(default=0)),
                ('bed_type', models.CharField(default='King Size', max_length=100)),
                ('virtual_tour_url', models.URLField(blank=True, help_text='Link to 3D virtual tour', null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed link', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='rooms', to='rooms.roomfacility')),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text for screen readers', max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
            },
        ),
        migrations.CreateModel(
            name='RoomPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Cancellation Policy, Pet Policy, Check-in rules', max_length=150)),
                ('description', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Policy',
                'verbose_name_plural': 'Room Policies',
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Christmas Season, Summer Special', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_override', models.DecimalField(decimal_places=2, help_text='Price per night during this period', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Seasonal Price',
                'verbose_name_plural': 'Room Seasonal Prices',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_dates', to='booking.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Availability',
                'verbose_name_plural': 'Room Availabilities',
                'unique_together': {('room', 'date')},
            },
        ),
    ]
