# Generated by Django 6.0.7 on 2026-07-14 11:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seodata',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('seo'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
