# Generated by Django 6.0.7 on 2026-07-15 07:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_seodata_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seodata',
            name='header_description',
            field=models.TextField(blank=True, help_text='Description text shown in the page header banner', null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Background image for the page banner', null=True, upload_to=core.utils.UploadTo('headers'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AddField(
            model_name='seodata',
            name='header_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle shown in the page header banner', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='header_title',
            field=models.CharField(blank=True, help_text='Main title shown in the page header banner', max_length=150, null=True),
        ),
    ]
