# Generated by Django 6.0.7 on 2026-07-18 10:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecreationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('spa', 'Spa & Wellness'), ('pool', 'Swimming Pool'), ('gym', 'Fitness Center / Gym'), ('kids', 'Kids Play Zone'), ('casino', 'Casino'), ('adventure', 'Adventure Activities'), ('safari', 'Wildlife Safari'), ('games', 'Games Area')], max_length=20)),
                ('description', models.TextField()),
                ('timings', models.CharField(help_text='e.g. 6:00 AM - 10:00 PM', max_length=100)),
                ('price_info', models.CharField(default='Complimentary for Guests', help_text='e.g. $50/Session or Free', max_length=100)),
                ('capacity', models.IntegerField(blank=True, help_text='Capacity if applicable', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('recreation'), validators=[core.utils.ValidateFileSize(2)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recreation & Activity',
                'verbose_name_plural': 'Recreation & Activities',
            },
        ),
    ]
